language: java
before_install:
  - git clone https://github.com/DevelopmentOnTheEdge/xmltest.git
    && cd xmltest
    && mvn install
    && cd ../
  - git clone https://github.com/DevelopmentOnTheEdge/beanexplorer.git
    && cd beanexplorer/beans
    && mvn install
    && cd ../../
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
jdk:
  - oraclejdk8
notifications:
  email: false
