systemSettings:
  type: dictionary
  displayName: System Settings
  primaryKey: _dummy_
  scheme:
    columns:
    - section_name:
        type: VARCHAR(255)
        defaultValue: '''system'''
    - setting_name:
        type: VARCHAR(64)
    - setting_value:
        type: TEXT
    indices:
    - I_UE_SS_SN_SN:
        unique: true
        columns:
        - section_name
        - setting_name
  queries:
  - All records:
      type: 1D
      roles: [SystemDeveloper, Administrator]
      invisible: true
      layout: '{"topForm":"TopFilter"}'
      operations:
      - Insert
      - Edit
      - Filter
      - TopFilter
      code: |-
        SELECT
          CONCAT(section_name, '|', setting_name) AS "___ID",
          section_name,
          setting_name,
          setting_value
        FROM systemSettings
  operations:
  - Insert:
      roles: [SystemDeveloper, Administrator]
      code: com.developmentontheedge.be5.server.operations.SilentInsertOperation
  - Edit:
      records: 1
      roles: [SystemDeveloper, Administrator]
      layout: '{"type":"modalForm"}'
      code: com.developmentontheedge.be5.modules.core.operations.system.SystemSettingsEdit
  - TopFilter:
      records: -1
      roles: [SystemDeveloper, Administrator]
      layout: '{"title":"Filter","properties":"section_name,setting_name"}'
      code: com.developmentontheedge.be5.server.operations.FilterOperation
  - Filter:
      records: -1
      roles: [SystemDeveloper, Administrator]
      code: com.developmentontheedge.be5.server.operations.FilterOperation
