/* Generated By:JJTree: Do not edit this line. AstBeSessionTag.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

import java.util.Set;

import one.util.streamex.StreamEx;

public class AstBeSessionTag extends AstBeNode
{
    private static final Set<String> ALLOWED_PARAMETERS = StreamEx.of( "refColumn", "default", "type" ).toSet();
    
    public AstBeSessionTag(int id)
    {
        super( id );
        tagName = "session";
        allowedParameters = ALLOWED_PARAMETERS;
    }
    
    private String name;

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Override
    public String getParametersString()
    {
        return ":"+name+super.getParametersString();
    }

    public String getDefault()
    {
        return getParameter( "default" );
    }
}
/* JavaCC - OriginalChecksum=5bfac9a483d6aca0b9aacdc100e73d4e (do not edit this line) */
