/* Generated By:JJTree: Do not edit this line. AstDelete.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

public class AstDelete extends SimpleNode
{
    public AstDelete(AstTableName tableName)
    {
        this( SqlParserTreeConstants.JJTDELETE );
        addChild(tableName);
    }

    public AstDelete(int id)
    {
        super(id);
        this.nodePrefix = "DELETE FROM";
    }

    public AstDelete(SqlParser p, int id)
    {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=b77107bb8ed6a82b48f5c2c832c3fb70 (do not edit this line) */
