/* Generated By:JJTree: Do not edit this line. AstDelete.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

import java.util.Iterator;
import java.util.Map;
import java.util.Objects;

public class AstDelete extends SimpleNode
{
    public AstDelete(AstTableName tableName)
    {
        this( SqlParserTreeConstants.JJTDELETE );
        addChild(tableName);
    }

    public AstDelete(int id)
    {
        super(id);
        this.nodePrefix = "DELETE FROM";
    }

    public AstDelete where(Map<String, String> conditions){
        Objects.requireNonNull(conditions);
        if(!conditions.isEmpty())setWhere(new AstWhere(conditions));
        return this;
    }

    public void setWhere(AstWhere where)
    {
        Objects.requireNonNull( where );
        AstWhere oldWhere = getWhere();
        if(oldWhere == null)
        {
            addChild(where);
        }
        else
        {
            oldWhere.replaceWith( where );
        }
    }

    public AstWhere getWhere()
    {
        return children().select( AstWhere.class ).findFirst().orElse( null );
    }

    public AstDelete(SqlParser p, int id)
    {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=b77107bb8ed6a82b48f5c2c832c3fb70 (do not edit this line) */
