/* Generated By:JJTree: Do not edit this line. AstInsertValues.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

public class AstInsertValues extends SimpleNode
{
    public AstInsertValues(int id)
    {
        super(id);
        this.nodePrefix = "VALUES (";
        this.nodeSuffix = ")";
        this.childrenDelimiter = ",";
    }

    public AstInsertValues(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8625c4c8db6e4bb5e885968ee8040626 (do not edit this line) */
