/* Generated By:JJTree: Do not edit this line. AstNullPredicate.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

public class AstNullPredicate extends SimpleNode
{
    public AstNullPredicate(int id)
    {
        super( id );
        this.nodeSuffix = "IS NULL";
    }

    Token isToken, notToken, nullToken;
    
    public SimpleNode getPredicand()
    {
        return child( 0 );
    }

    public Token getIsToken()
    {
        return isToken;
    }

    public void setIsToken(Token isToken)
    {
        this.isToken = isToken;
    }

    public Token getNotToken()
    {
        return notToken;
    }

    public void setNotToken(Token notToken)
    {
        this.notToken = notToken;
        this.nodeSuffix = notToken == null ? "IS NULL" : "IS NOT NULL";
    }

    public Token getNullToken()
    {
        return nullToken;
    }

    public void setNullToken(Token nullToken)
    {
        this.nullToken = nullToken;
    }
}
/* JavaCC - OriginalChecksum=427413ce22dc6bf7ea02cb783644e625 (do not edit this line) */
