/* Generated By:JJTree: Do not edit this line. AstTableName.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

public class AstTableName extends SimpleNode
{
    public AstTableName(int id)
    {
        super( id );
        this.childrenDelimiter = ".";
    }

    public String getValue()
    {
        return format().trim();
    }

    public void setValue(String value)
    {
        this.removeChildren();
        String[] parts = value.split( "[.]" );
        for( String part : parts )
            addChild( new AstIdentifierConstant( part ) );
    }
}
/* JavaCC - OriginalChecksum=029050d4e903c4c166e9af2cb3f75027 (do not edit this line) */
