/* Generated By:JJTree: Do not edit this line. AstUpdateSetItem.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

public class AstUpdateSetItem extends SimpleNode
{
    public AstUpdateSetItem(int id)
    {
        super(id);
    }

    public AstUpdateSetItem(SqlParser p, int id)
    {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=2d2ef14f6ac0af9b95689a59af95a989 (do not edit this line) */
