/* Generated By:JJTree: Do not edit this line. AstWhere.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

public class AstWhere extends SimpleNode
{
    public AstWhere(SimpleNode node)
    {
        this(SqlParserTreeConstants.JJTWHERE);
        addChild( node );
    }

    public AstWhere(int id)
    {
        super( id );
        this.nodePrefix = "WHERE";
    }

    public AstWhere()
    {
        this(SqlParserTreeConstants.JJTWHERE);
    }
}
/* JavaCC - OriginalChecksum=03171975e291b8bf905931f781821b13 (do not edit this line) */
