/* Generated By:JJTree: Do not edit this line. AstWhere.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.developmentontheedge.sql.model;

import java.util.Iterator;
import java.util.Map;

public class AstWhere extends SimpleNode
{
    public AstWhere(Map<String, String> conditions)
    {
        this(SqlParserTreeConstants.JJTWHERE);
        if(conditions.size() > 0 )
        {
            Iterator<Map.Entry<String, String>> iterator = conditions.entrySet().iterator();
            iterator.hasNext();
            addChild(addAstFunNode(iterator));
        }
    }

    private SimpleNode addAstFunNode(Iterator<Map.Entry<String, String>> iterator) {
//        TODO add !=, NOT LIKE
//        var udIDs = database.utilityDocuments.ids( {
//                externalStatus: "!=ok"
//        } );
        Map.Entry<String, String> entry = iterator.next();
        String value = entry.getValue();
        PredefinedFunction function = DefaultParserContext.FUNC_EQ;
        SimpleNode astFunNode;

        if(value.equals("null") || value.equals("notNull"))
        {
            astFunNode = new AstNullPredicate(value.equals("null"), new AstFieldReference(entry.getKey()));
        }
        else
        {
            if(value.endsWith("%") || value.startsWith("%"))
            {
                function = DefaultParserContext.FUNC_LIKE;
            }
            astFunNode = function.node(new AstFieldReference(entry.getKey()), new AstReplacementParameter());
        }

        if(iterator.hasNext()){
            return new AstBooleanTerm(astFunNode, addAstFunNode(iterator));
        }else{
            return astFunNode;
        }

    }

    public AstWhere(int id)
    {
        super( id );
        this.nodePrefix = "WHERE";
    }

    public AstWhere()
    {
        this(SqlParserTreeConstants.JJTWHERE);
    }
}
/* JavaCC - OriginalChecksum=03171975e291b8bf905931f781821b13 (do not edit this line) */
