core:
  moduleProject: true
  features: []
  l10n: ru
  projectFileStructure: {}
  modules: []
  application:
  - _logout_
  - _system_
  - categories
  - classifications
  - countries
  - icons
  - languages
  - mimeTypes
  - provinces
  - sequences
  - systemSettings
  - user_roles
  - user_prefs
  - users
  scripts:
  - Post-db
  - Pre-db
  - dict/countries
  - dict/languages
  - dict/mimeTypes
  - dict/systemSettings
  - dict/provinces
  - dictionaries
  - procedures_oracle
  - procedures_postgres
  - procedures_sqlserver
  includes:
  - common
  - core
