core:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  moduleProject: true
  features:
  - compiledGroovy
  l10n: ru
  modules: []
  application:
  - _logout_
  - _system_
  - _categoriesService_
  - be5eventParams
  - be5events
  - be5operationLogParams
  - be5operationLogs
  - categories
  - classifications
  - columnSettings
  - countries
  - entities
  - languages
  - mimeTypes
  - provinces
  - roles
  - sequences
  - systemSettings
  - user_roles
  - user_prefs
  - users
  scripts:
  - Post-db
  - Pre-db
  - dict/countries
  - dict/languages
  - dict/mimeTypes
  - dict/systemSettings
  - dict/provinces
  - dictionaries
  - procedures_oracle
  - procedures_postgres
  - procedures_sqlserver
  includes:
  - common
  - core
