delete from countries;

insert into countries( ID, name, telCode ) values( 'AF', 'Afghanistan', '+93' );
insert into countries( ID, name, telCode ) values( 'AL', 'Albania', '+355' );
insert into countries( ID, name, telCode ) values( 'DZ', 'Algeria', '+213' );
insert into countries( ID, name, telCode ) values( 'AS', 'American Samoa', '+684' );
insert into countries( ID, name, telCode ) values( 'AD', 'Andorra', '+376' );
insert into countries( ID, name, telCode ) values( 'AO', 'Angola', '+244' );
insert into countries( ID, name, telCode ) values( 'AI', 'Anguilla', '+1/264' );
insert into countries( ID, name, telCode ) values( 'AQ', 'Antarctica', '+672' );
insert into countries( ID, name, telCode ) values( 'AG', 'Antigua and Barbuda', '+1/268' );
insert into countries( ID, name, telCode ) values( 'AR', 'Argentina', '+54' );
insert into countries( ID, name, telCode ) values( 'AM', 'Armenia', '+374' );
insert into countries( ID, name, telCode ) values( 'AW', 'Aruba', '+297' );
insert into countries( ID, name, telCode ) values( 'AU', 'Australia', '+61' );
insert into countries( ID, name, telCode ) values( 'AT', 'Austria', '+43' );
insert into countries( ID, name, telCode ) values( 'AZ', 'Azerbaijan', '+994' );
insert into countries( ID, name, telCode ) values( 'BS', 'Bahamas', '+1/242' );
insert into countries( ID, name, telCode ) values( 'BH', 'Bahrain', '+973' );
insert into countries( ID, name, telCode ) values( 'BD', 'Bangladesh', '+880' );
insert into countries( ID, name, telCode ) values( 'BB', 'Barbados', '+1/246' );
insert into countries( ID, name, telCode ) values( 'BY', 'Belarus', '+375' );
insert into countries( ID, name, telCode ) values( 'BE', 'Belgium', '+32' );
insert into countries( ID, name, telCode ) values( 'BZ', 'Belize', '+501' );
insert into countries( ID, name, telCode ) values( 'BJ', 'Benin', '+229' );
insert into countries( ID, name, telCode ) values( 'BM', 'Bermuda', '+1/441' );
insert into countries( ID, name, telCode ) values( 'BT', 'Bhutan', '+975' );
insert into countries( ID, name, telCode ) values( 'BO', 'Bolivia', '+591' );
insert into countries( ID, name, telCode ) values( 'BA', 'Bosnia and Herzegovina', '+387' );
insert into countries( ID, name, telCode ) values( 'BW', 'Botswana', '+267' );
insert into countries( ID, name ) values( 'BV', 'Bouvet Island' );
insert into countries( ID, name, telCode ) values( 'BR', 'Brazil', '+55' );
insert into countries( ID, name ) values( 'IO', 'British Indian Ocean Territory' );
insert into countries( ID, name, telCode ) values( 'BN', 'Brunei Darussalam', '+673' );
insert into countries( ID, name, telCode ) values( 'BG', 'Bulgaria', '+359' );
insert into countries( ID, name, telCode ) values( 'BF', 'Burkina Faso', '+226' );
insert into countries( ID, name, telCode ) values( 'BI', 'Burundi', '+257' );
insert into countries( ID, name, telCode ) values( 'KH', 'Cambodia', '+855' );
insert into countries( ID, name, telCode ) values( 'CM', 'Cameroon', '+237' );
insert into countries( ID, name, telCode ) values( 'CA', 'Canada', '+1' );
insert into countries( ID, name, telCode ) values( 'CV', 'Cape Verde', '+238' );
insert into countries( ID, name, telCode ) values( 'KY', 'Cayman Islands', '+1/345' );
insert into countries( ID, name, telCode ) values( 'CF', 'Central African Republic', '+236' );
insert into countries( ID, name, telCode ) values( 'TD', 'Chad', '+235' );
insert into countries( ID, name, telCode ) values( 'CL', 'Chile', '+56' );
insert into countries( ID, name, telCode ) values( 'CN', 'China', '+86' );
insert into countries( ID, name, telCode ) values( 'CX', 'Christmas Island', '+61/08' );
insert into countries( ID, name, telCode ) values( 'CC', 'Cocos (Keeling) Islands', '+61' );
insert into countries( ID, name, telCode ) values( 'CO', 'Colombia', '+57' );
insert into countries( ID, name, telCode ) values( 'KM', 'Comoros', '+269' );
insert into countries( ID, name, telCode ) values( 'CG', 'Congo', '+242' );
insert into countries( ID, name, telCode ) values( 'CK', 'Cook Islands', '+682' );
insert into countries( ID, name, telCode ) values( 'CR', 'Costa Rica', '+506' );
insert into countries( ID, name, telCode ) values( 'CI', 'Cote D''Ivoire (Ivory Coast)', '+225' );
insert into countries( ID, name, telCode ) values( 'HR', 'Croatia (Hrvatska)', '+385' );
insert into countries( ID, name, telCode ) values( 'CU', 'Cuba', '+53' );
insert into countries( ID, name, telCode ) values( 'CY', 'Cyprus', '+357' );
insert into countries( ID, name, telCode ) values( 'CZ', 'Czech Republic', '+420' );
insert into countries( ID, name, telCode ) values( 'DK', 'Denmark', '+45' );
insert into countries( ID, name, telCode ) values( 'DJ', 'Djibouti', '+253' );
insert into countries( ID, name, telCode ) values( 'DM', 'Dominica', '+1/767' );
insert into countries( ID, name, telCode ) values( 'DO', 'Dominican Republic', '+1/809' );
insert into countries( ID, name, telCode ) values( 'TP', 'East Timor', '+670' );
insert into countries( ID, name, telCode ) values( 'EC', 'Ecuador', '+593' );
insert into countries( ID, name, telCode ) values( 'EG', 'Egypt', '+20' );
insert into countries( ID, name, telCode ) values( 'SV', 'El Salvador', '+503' );
insert into countries( ID, name, telCode ) values( 'GQ', 'Equatorial Guinea', '+240' );
insert into countries( ID, name, telCode ) values( 'ER', 'Eritrea', '+291' );
insert into countries( ID, name, telCode ) values( 'EE', 'Estonia', '+372' );
insert into countries( ID, name, telCode ) values( 'ET', 'Ethiopia', '+251' );
insert into countries( ID, name, telCode ) values( 'FK', 'Falkland Islands (Malvinas)', '+500' );
insert into countries( ID, name, telCode ) values( 'FO', 'Faroe Islands', '+298' );
insert into countries( ID, name, telCode ) values( 'FJ', 'Fiji', '+679' );
insert into countries( ID, name, telCode ) values( 'FI', 'Finland', '+358' );
insert into countries( ID, name, telCode ) values( 'FR', 'France', '+33' );
insert into countries( ID, name, telCode ) values( 'GF', 'French Guiana', '+594' );
insert into countries( ID, name, telCode ) values( 'PF', 'French Polynesia', '+689' );
insert into countries( ID, name ) values( 'TF', 'French Southern Territories' );
insert into countries( ID, name, telCode ) values( 'GA', 'Gabon', '+241' );
insert into countries( ID, name, telCode ) values( 'GM', 'Gambia', '+220' );
insert into countries( ID, name, telCode ) values( 'GE', 'Georgia', '+995' );
insert into countries( ID, name, telCode ) values( 'DE', 'Germany', '+49' );
insert into countries( ID, name, telCode ) values( 'GH', 'Ghana', '+233' );
insert into countries( ID, name, telCode ) values( 'GI', 'Gibraltar', '+350' );
insert into countries( ID, name, telCode ) values( 'GR', 'Greece', '+30' );
insert into countries( ID, name, telCode ) values( 'GL', 'Greenland', '+299' );
insert into countries( ID, name, telCode ) values( 'GD', 'Grenada', '+1/473' );
insert into countries( ID, name, telCode ) values( 'GP', 'Guadeloupe', '+590' );
insert into countries( ID, name, telCode ) values( 'GU', 'Guam', '+1/671' );
insert into countries( ID, name, telCode ) values( 'GT', 'Guatemala', '+502' );
insert into countries( ID, name, telCode ) values( 'GN', 'Guinea', '+224' );
insert into countries( ID, name, telCode ) values( 'GW', 'Guinea-Bissau', '+245' );
insert into countries( ID, name, telCode ) values( 'GY', 'Guyana', '+592' );
insert into countries( ID, name, telCode ) values( 'HT', 'Haiti', '+509' );
insert into countries( ID, name ) values( 'HM', 'Heard and McDonald Islands' );
insert into countries( ID, name, telCode ) values( 'HN', 'Honduras', '+504' );
insert into countries( ID, name, telCode ) values( 'HK', 'Hong Kong', '+852' );
insert into countries( ID, name, telCode ) values( 'HU', 'Hungary', '+36' );
insert into countries( ID, name, telCode ) values( 'IS', 'Iceland', '+354' );
insert into countries( ID, name, telCode ) values( 'IN', 'India', '+91' );
insert into countries( ID, name, telCode ) values( 'ID', 'Indonesia', '+62' );
insert into countries( ID, name, telCode ) values( 'IR', 'Iran', '+98' );
insert into countries( ID, name, telCode ) values( 'IQ', 'Iraq', '+964' );
insert into countries( ID, name, telCode ) values( 'IE', 'Ireland', '+353' );
insert into countries( ID, name, telCode ) values( 'IL', 'Israel', '+972' );
insert into countries( ID, name, telCode ) values( 'IT', 'Italy', '+39' );
insert into countries( ID, name, telCode ) values( 'JM', 'Jamaica', '+1/876' );
insert into countries( ID, name, telCode ) values( 'JP', 'Japan', '+81' );
insert into countries( ID, name, telCode ) values( 'JO', 'Jordan', '+962' );
insert into countries( ID, name, telCode ) values( 'KZ', 'Kazakhstan', '+7' );
insert into countries( ID, name, telCode ) values( 'KE', 'Kenya', '+254' );
insert into countries( ID, name, telCode ) values( 'KI', 'Kiribati', '+686' );
insert into countries( ID, name, telCode ) values( 'KP', 'Korea (North)', '+850' );
insert into countries( ID, name, telCode ) values( 'KR', 'Korea (South)', '+82' );
insert into countries( ID, name, telCode ) values( 'KW', 'Kuwait', '+965' );
insert into countries( ID, name, telCode ) values( 'KG', 'Kyrgyzstan', '+996' );
insert into countries( ID, name, telCode ) values( 'LA', 'Laos', '+856' );
insert into countries( ID, name, telCode ) values( 'LV', 'Latvia', '+371' );
insert into countries( ID, name, telCode ) values( 'LB', 'Lebanon', '+961' );
insert into countries( ID, name, telCode ) values( 'LS', 'Lesotho', '+266' );
insert into countries( ID, name, telCode ) values( 'LR', 'Liberia', '+231' );
insert into countries( ID, name, telCode ) values( 'LY', 'Libya', '+218' );
insert into countries( ID, name, telCode ) values( 'LI', 'Liechtenstein', '+423' );
insert into countries( ID, name, telCode ) values( 'LT', 'Lithuania', '+370' );
insert into countries( ID, name, telCode ) values( 'LU', 'Luxembourg', '+352' );
insert into countries( ID, name, telCode ) values( 'MO', 'Macau', '+853' );
insert into countries( ID, name, telCode ) values( 'MK', 'Macedonia', '+389' );
insert into countries( ID, name, telCode ) values( 'MG', 'Madagascar', '+261' );
insert into countries( ID, name, telCode ) values( 'MW', 'Malawi', '+265' );
insert into countries( ID, name, telCode ) values( 'MY', 'Malaysia', '+60' );
insert into countries( ID, name, telCode ) values( 'MV', 'Maldives', '+960' );
insert into countries( ID, name, telCode ) values( 'ML', 'Mali', '+223' );
insert into countries( ID, name, telCode ) values( 'MT', 'Malta', '+356' );
insert into countries( ID, name, telCode ) values( 'MH', 'Marshall Islands', '+692' );
insert into countries( ID, name, telCode ) values( 'MQ', 'Martinique', '+596' );
insert into countries( ID, name, telCode ) values( 'MR', 'Mauritania', '+222' );
insert into countries( ID, name, telCode ) values( 'MU', 'Mauritius', '+230' );
insert into countries( ID, name, telCode ) values( 'YT', 'Mayotte', '+269' );
insert into countries( ID, name, telCode ) values( 'MX', 'Mexico', '+52' );
insert into countries( ID, name, telCode ) values( 'FM', 'Micronesia', '+691' );
insert into countries( ID, name, telCode ) values( 'MD', 'Moldova', '+373' );
insert into countries( ID, name, telCode ) values( 'MC', 'Monaco', '+377' );
insert into countries( ID, name, telCode ) values( 'MN', 'Mongolia', '+976' );
insert into countries( ID, name, telCode ) values( 'MS', 'Montserrat', '+1/664' );
insert into countries( ID, name, telCode ) values( 'MA', 'Morocco', '+212' );
insert into countries( ID, name, telCode ) values( 'MZ', 'Mozambique', '+258' );
insert into countries( ID, name, telCode ) values( 'MM', 'Myanmar', '+95' );
insert into countries( ID, name, telCode ) values( 'NA', 'Namibia', '+264' );
insert into countries( ID, name, telCode ) values( 'NR', 'Nauru', '+674' );
insert into countries( ID, name, telCode ) values( 'NP', 'Nepal', '+977' );
insert into countries( ID, name, telCode ) values( 'NL', 'Netherlands', '+31' );
insert into countries( ID, name, telCode ) values( 'AN', 'Netherlands Antilles', '+599' );
insert into countries( ID, name ) values( 'NT', 'Neutral Zone' );
insert into countries( ID, name, telCode ) values( 'NC', 'New Caledonia', '+687' );
insert into countries( ID, name, telCode ) values( 'NZ', 'New Zealand', '+64' );
insert into countries( ID, name, telCode ) values( 'NI', 'Nicaragua', '+505' );
insert into countries( ID, name, telCode ) values( 'NE', 'Niger', '+227' );
insert into countries( ID, name, telCode ) values( 'NG', 'Nigeria', '+234' );
insert into countries( ID, name, telCode ) values( 'NU', 'Niue', '+672' );
insert into countries( ID, name, telCode ) values( 'NF', 'Norfolk Island', '+672' );
insert into countries( ID, name, telCode ) values( 'MP', 'Northern Mariana Islands', '+1/670' );
insert into countries( ID, name, telCode ) values( 'NO', 'Norway', '+47' );
insert into countries( ID, name, telCode ) values( 'OM', 'Oman', '+968' );
insert into countries( ID, name, telCode ) values( 'PK', 'Pakistan', '+92' );
insert into countries( ID, name, telCode ) values( 'PW', 'Palau', '+680' );
insert into countries( ID, name, telCode ) values( 'PA', 'Panama', '+507' );
insert into countries( ID, name, telCode ) values( 'PG', 'Papua New Guinea', '+675' );
insert into countries( ID, name, telCode ) values( 'PY', 'Paraguay', '+595' );
insert into countries( ID, name, telCode ) values( 'PE', 'Peru', '+51' );
insert into countries( ID, name, telCode ) values( 'PH', 'Philippines', '+63' );
insert into countries( ID, name ) values( 'PN', 'Pitcairn' );
insert into countries( ID, name, telCode ) values( 'PL', 'Poland', '+48' );
insert into countries( ID, name, telCode ) values( 'PT', 'Portugal', '+351' );
insert into countries( ID, name, telCode ) values( 'PR', 'Puerto Rico', '+1/787' );
insert into countries( ID, name, telCode ) values( 'QA', 'Qatar', '+974' );
insert into countries( ID, name, telCode ) values( 'RE', 'Reunion', '+262' );
insert into countries( ID, name, telCode ) values( 'RO', 'Romania', '+40' );
insert into countries( ID, name, telCode ) values( 'RU', 'Russian Federation', '+7' );
insert into countries( ID, name, telCode ) values( 'RW', 'Rwanda', '+250' );
insert into countries( ID, name ) values( 'GS', 'S. Georgia and S. Sandwich Isls.' );
insert into countries( ID, name, telCode ) values( 'KN', 'Saint Kitts and Nevis', '+1/869' );
insert into countries( ID, name, telCode ) values( 'LC', 'Saint Lucia', '+1/758' );
insert into countries( ID, name, telCode ) values( 'VC', 'Saint Vincent and the Grenadines', '+1/784' );
insert into countries( ID, name ) values( 'WS', 'Samoa' );
insert into countries( ID, name, telCode ) values( 'SM', 'San Marino', '+378' );
insert into countries( ID, name, telCode ) values( 'ST', 'Sao Tome and Principe', '+239' );
insert into countries( ID, name, telCode ) values( 'SA', 'Saudi Arabia', '+966' );
insert into countries( ID, name, telCode ) values( 'SN', 'Senegal', '+221' );
insert into countries( ID, name, telCode ) values( 'SC', 'Seychelles', '+248' );
insert into countries( ID, name, telCode ) values( 'SL', 'Sierra Leone', '+232' );
insert into countries( ID, name, telCode ) values( 'SG', 'Singapore', '+65' );
insert into countries( ID, name, telCode ) values( 'SK', 'Slovak Republic', '+421' );
insert into countries( ID, name, telCode ) values( 'SI', 'Slovenia', '+386' );
insert into countries( ID, name, telCode ) values( 'SB', 'Solomon Islands', '+677' );
insert into countries( ID, name, telCode ) values( 'SO', 'Somalia', '+252' );
insert into countries( ID, name, telCode ) values( 'ZA', 'South Africa', '+27' );
insert into countries( ID, name, telCode ) values( 'ES', 'Spain', '+34' );
insert into countries( ID, name, telCode ) values( 'LK', 'Sri Lanka', '+94' );
insert into countries( ID, name, telCode ) values( 'SH', 'St. Helena', '+290' );
insert into countries( ID, name ) values( 'PM', 'St. Pierre and Miquelon' );
insert into countries( ID, name, telCode ) values( 'SD', 'Sudan', '+249' );
insert into countries( ID, name, telCode ) values( 'SR', 'Suriname', '+597' );
insert into countries( ID, name ) values( 'SJ', 'Svalbard and Jan Mayen Islands' );
insert into countries( ID, name, telCode ) values( 'SZ', 'Swaziland', '+268' );
insert into countries( ID, name, telCode ) values( 'SE', 'Sweden', '+46' );
insert into countries( ID, name, telCode ) values( 'CH', 'Switzerland', '+41' );
insert into countries( ID, name, telCode ) values( 'SY', 'Syria', '+963' );
insert into countries( ID, name, telCode ) values( 'TW', 'Taiwan', '+886' );
insert into countries( ID, name, telCode ) values( 'TJ', 'Tajikistan', '+992' );
insert into countries( ID, name, telCode ) values( 'TZ', 'Tanzania', '+255' );
insert into countries( ID, name, telCode ) values( 'TH', 'Thailand', '+66' );
insert into countries( ID, name, telCode ) values( 'TG', 'Togo', '+228' );
insert into countries( ID, name, telCode ) values( 'TK', 'Tokelau', '+690' );
insert into countries( ID, name, telCode ) values( 'TO', 'Tonga', '+676' );
insert into countries( ID, name, telCode ) values( 'TT', 'Trinidad and Tobago', '+1/868' );
insert into countries( ID, name, telCode ) values( 'TN', 'Tunisia', '+216' );
insert into countries( ID, name, telCode ) values( 'TR', 'Turkey', '+90' );
insert into countries( ID, name, telCode ) values( 'TM', 'Turkmenistan', '+993' );
insert into countries( ID, name, telCode ) values( 'TC', 'Turks and Caicos Islands', '+1/649' );
insert into countries( ID, name, telCode ) values( 'TV', 'Tuvalu', '+688' );
insert into countries( ID, name ) values( 'UM', 'US Minor Outlying Islands' );
insert into countries( ID, name, telCode ) values( 'UG', 'Uganda', '+256' );
insert into countries( ID, name, telCode ) values( 'UA', 'Ukraine', '+380' );
insert into countries( ID, name, telCode ) values( 'AE', 'United Arab Emirates', '+971' );
insert into countries( ID, name, telCode ) values( 'UK', 'United Kingdom', '+44' );
insert into countries( ID, name, telCode ) values( 'US', 'United States', '+1' );
insert into countries( ID, name, telCode ) values( 'UY', 'Uruguay', '+598' );
insert into countries( ID, name, telCode ) values( 'UZ', 'Uzbekistan', '+998' );
insert into countries( ID, name, telCode ) values( 'VU', 'Vanuatu', '+678' );
insert into countries( ID, name, telCode ) values( 'VA', 'Vatican City State (Holy See)', '+39' );
insert into countries( ID, name, telCode ) values( 'VE', 'Venezuela', '+58' );
insert into countries( ID, name, telCode ) values( 'VN', 'Viet Nam', '+84' );
insert into countries( ID, name, telCode ) values( 'VG', 'Virgin Islands (British)', '+1/284' );
insert into countries( ID, name, telCode ) values( 'VI', 'Virgin Islands (U.S.)', '+1/340' );
insert into countries( ID, name, telCode ) values( 'WF', 'Wallis and Futuna Islands', '+681' );
insert into countries( ID, name ) values( 'EH', 'Western Sahara' );
insert into countries( ID, name, telCode ) values( 'YE', 'Yemen', '+967' );
insert into countries( ID, name, telCode ) values( 'YU', 'Yugoslavia', '+381' );
insert into countries( ID, name, telCode ) values( 'ZR', 'Congo, Dem. Rep. of  (former Zaire)', '+243' );
insert into countries( ID, name, telCode ) values( 'ZM', 'Zambia', '+260' );
insert into countries( ID, name, telCode ) values( 'ZW', 'Zimbabwe', '+263' );
